[package]
name = "riker-dispatcher"
version = "0.1.9"
authors = ["Lee Smith <leenozara@gmail.com>"]
edition = "2018"
description = "A Dispatcher module for Riker powered by `Futures::execution::ThreadPool`"
homepage = "https://riker.rs"
repository = "https://github.com/riker-rs/riker-default"
license = "MIT"
readme = "README.md"

[dependencies]
<<<<<<< d48c2e162dbd2825d597bae1d5ae92e8e352980b
riker = { path = "../../", version = "0.1.9" }
config = "0.9"
futures-preview = "0.2.2"
=======
riker = { path = "../../", version = "0.1.8" }
config = "0.8"
# futures-preview = "0.2.2"
futures-preview = "0.3.0-alpha.10"
>>>>>>> Actors and Futures run with catch_unwind
futures-cpupool = "0.1.8"
